var player = [
    {
        playerId : 0,
        playerName : "苟仲文",
        playerAttackValue : 0,
        playerDefendValue : 0,
        playerSpeedValue : 0,
        playerPosition : 2,
    },
    {
        playerId : 1,
        playerName : "C罗",
        playerAttackValue : 92,
        playerDefendValue : 33,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 2,
        playerName : "贝尔",
        playerAttackValue : 100,
        playerDefendValue : 57,
        playerSpeedValue : 100,
        playerPosition : 0,
    },
    {
        playerId : 3,
        playerName : "奥巴梅扬",
        playerAttackValue : 84,
        playerDefendValue : 37,
        playerSpeedValue : 96,
        playerPosition : 0,
    },
    {
        playerId : 4,
        playerName : "梅西",
        playerAttackValue : 90,
        playerDefendValue : 26,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 5,
        playerName : "阿圭罗",
        playerAttackValue : 88,
        playerDefendValue : 23,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 6,
        playerName : "罗伊斯",
        playerAttackValue : 85,
        playerDefendValue : 40,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 7,
        playerName : "迪巴拉",
        playerAttackValue : 87,
        playerDefendValue : 24,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 8,
        playerName : "内马尔",
        playerAttackValue : 84,
        playerDefendValue : 30,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 9,
        playerName : "瓦尔迪",
        playerAttackValue : 80,
        playerDefendValue : 54,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 10,
        playerName : "苏亚雷斯",
        playerAttackValue : 90,
        playerDefendValue : 42,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 11,
        playerName : "胡尔克",
        playerAttackValue : 87,
        playerDefendValue : 43,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 12,
        playerName : "格列兹曼",
        playerAttackValue : 85,
        playerDefendValue : 30,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 13,
        playerName : "阿扎尔",
        playerAttackValue : 81,
        playerDefendValue : 32,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 14,
        playerName : "罗本",
        playerAttackValue : 85,
        playerDefendValue : 32,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 15,
        playerName : "沃尔科特",
        playerAttackValue : 77,
        playerDefendValue : 38,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 16,
        playerName : "桑切斯",
        playerAttackValue : 84,
        playerDefendValue : 40,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 17,
        playerName : "马夏尔",
        playerAttackValue : 79,
        playerDefendValue : 42,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 18,
        playerName : "道格拉斯-科斯塔",
        playerAttackValue : 78,
        playerDefendValue : 49,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 19,
        playerName : "雷米",
        playerAttackValue : 80,
        playerDefendValue : 34,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 20,
        playerName : "伊尼亚基-威廉姆斯",
        playerAttackValue : 75,
        playerDefendValue : 34,
        playerSpeedValue : 94,
        playerPosition : 0,
    },
    {
        playerId : 21,
        playerName : "拉卡泽特",
        playerAttackValue : 83,
        playerDefendValue : 38,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 22,
        playerName : "马内",
        playerAttackValue : 76,
        playerDefendValue : 36,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 23,
        playerName : "金斯利-科曼",
        playerAttackValue : 76,
        playerDefendValue : 19,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 24,
        playerName : "科诺普良卡",
        playerAttackValue : 79,
        playerDefendValue : 33,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 25,
        playerName : "许尔勒",
        playerAttackValue : 81,
        playerDefendValue : 36,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 26,
        playerName : "莱万多夫斯基",
        playerAttackValue : 87,
        playerDefendValue : 38,
        playerSpeedValue : 81,
        playerPosition : 0,
    },
    {
        playerId : 27,
        playerName : "夸德拉多",
        playerAttackValue : 76,
        playerDefendValue : 58,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 28,
        playerName : "卡列洪",
        playerAttackValue : 78,
        playerDefendValue : 35,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 29,
        playerName : "马丁斯",
        playerAttackValue : 77,
        playerDefendValue : 33,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 30,
        playerName : "萨内",
        playerAttackValue : 75,
        playerDefendValue : 35,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 31,
        playerName : "阿尔巴",
        playerAttackValue : 69,
        playerDefendValue : 81,
        playerSpeedValue : 93,
        playerPosition : 1,
    },
    {
        playerId : 32,
        playerName : "凯尔-沃克",
        playerAttackValue : 63,
        playerDefendValue : 79,
        playerSpeedValue : 90,
        playerPosition : 1,
    },
    {
        playerId : 33,
        playerName : "阿拉巴",
        playerAttackValue : 73,
        playerDefendValue : 82,
        playerSpeedValue : 86,
        playerPosition : 1,
    },
    {
        playerId : 34,
        playerName : "塞梅多",
        playerAttackValue : 54,
        playerDefendValue : 75,
        playerSpeedValue : 92,
        playerPosition : 1,
    },
    {
        playerId : 35,
        playerName : "安东尼奥-瓦伦西亚",
        playerAttackValue : 66,
        playerDefendValue : 79,
        playerSpeedValue : 87,
        playerPosition : 1,
    },
    {
        playerId : 36,
        playerName : "阿莱士-桑德罗",
        playerAttackValue : 64,
        playerDefendValue : 79,
        playerSpeedValue : 87,
        playerPosition : 1,
    },
    {
        playerId : 37,
        playerName : "拜利",
        playerAttackValue : 42,
        playerDefendValue : 84,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 38,
        playerName : "阿尔维斯",
        playerAttackValue : 70,
        playerDefendValue : 78,
        playerSpeedValue : 87,
        playerPosition : 1,
    },
    {
        playerId : 39,
        playerName : "奥里耶",
        playerAttackValue : 66,
        playerDefendValue : 80,
        playerSpeedValue : 85,
        playerPosition : 1,
    },
    {
        playerId : 40,
        playerName : "克莱因",
        playerAttackValue : 61,
        playerDefendValue : 79,
        playerSpeedValue : 86,
        playerPosition : 1,
    },
    {
        playerId : 41,
        playerName : "拉莫斯",
        playerAttackValue : 63,
        playerDefendValue : 87,
        playerSpeedValue : 78,
        playerPosition : 1,
    },
    {
        playerId : 42,
        playerName : "卢克-肖",
        playerAttackValue : 51,
        playerDefendValue : 79,
        playerSpeedValue : 86,
        playerPosition : 1,
    },
    {
        playerId : 43,
        playerName : "蒂亚戈-席尔瓦",
        playerAttackValue : 57,
        playerDefendValue : 90,
        playerSpeedValue : 74,
        playerPosition : 1,
    },
    {
        playerId : 44,
        playerName : "马里奥-加斯帕尔",
        playerAttackValue : 70,
        playerDefendValue : 80,
        playerSpeedValue : 83,
        playerPosition : 1,
    },
    {
        playerId : 45,
        playerName : "坎特",
        playerAttackValue : 66,
        playerDefendValue : 81,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 46,
        playerName : "加亚",
        playerAttackValue : 58,
        playerDefendValue : 75,
        playerSpeedValue : 88,
        playerPosition : 1,
    },
    {
        playerId : 47,
        playerName : "胡安弗兰",
        playerAttackValue : 58,
        playerDefendValue : 79,
        playerSpeedValue : 84,
        playerPosition : 1,
    },
    {
        playerId : 48,
        playerName : "阿斯皮利奎塔",
        playerAttackValue : 56,
        playerDefendValue : 84,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 49,
        playerName : "卡瓦哈尔",
        playerAttackValue : 45,
        playerDefendValue : 81,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 50,
        playerName : "科斯切尔尼",
        playerAttackValue : 40,
        playerDefendValue : 85,
        playerSpeedValue : 78,
        playerPosition : 1,
    },
    {
        playerId : 51,
        playerName : "德马科斯",
        playerAttackValue : 62,
        playerDefendValue : 74,
        playerSpeedValue : 88,
        playerPosition : 1,
    },
    {
        playerId : 52,
        playerName : "马图伊迪",
        playerAttackValue : 67,
        playerDefendValue : 83,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 53,
        playerName : "菲利佩",
        playerAttackValue : 62,
        playerDefendValue : 82,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 54,
        playerName : "瓦拉内",
        playerAttackValue : 45,
        playerDefendValue : 85,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 55,
        playerName : "马塞洛",
        playerAttackValue : 69,
        playerDefendValue : 82,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 56,
        playerName : "杜桑-巴斯塔",
        playerAttackValue : 67,
        playerDefendValue : 80,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 57,
        playerName : "蒙托亚",
        playerAttackValue : 50,
        playerDefendValue : 75,
        playerSpeedValue : 86,
        playerPosition : 1,
    },
    {
        playerId : 58,
        playerName : "斯莫林",
        playerAttackValue : 46,
        playerDefendValue : 84,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 59,
        playerName : "亚历克斯-比达尔",
        playerAttackValue : 67,
        playerDefendValue : 69,
        playerSpeedValue : 91,
        playerPosition : 1,
    },
    {
        playerId : 60,
        playerName : "科尔曼",
        playerAttackValue : 68,
        playerDefendValue : 81,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 61,
        playerName : "丹尼-罗斯",
        playerAttackValue : 63,
        playerDefendValue : 78,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 62,
        playerName : "洛里",
        playerAttackValue : 1,
        playerDefendValue : 87,
        playerSpeedValue : 64,
        playerPosition : 2,
    },
    {
        playerId : 63,
        playerName : "诺伊尔",
        playerAttackValue : 1,
        playerDefendValue : 89,
        playerSpeedValue : 60,
        playerPosition : 2,
    },
    {
        playerId : 64,
        playerName : "安东尼-洛佩斯",
        playerAttackValue : 1,
        playerDefendValue : 86,
        playerSpeedValue : 62,
        playerPosition : 2,
    },
    {
        playerId : 65,
        playerName : "埃德森-莫赖斯",
        playerAttackValue : 1,
        playerDefendValue : 81,
        playerSpeedValue : 63,
        playerPosition : 2,
    },
    {
        playerId : 66,
        playerName : "卡斯帕-舒梅切尔",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 61,
        playerPosition : 2,
    },
    {
        playerId : 67,
        playerName : "乔-哈特",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 60,
        playerPosition : 2,
    },
    {
        playerId : 68,
        playerName : "德赫亚",
        playerAttackValue : 1,
        playerDefendValue : 88,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 69,
        playerName : "纳瓦斯",
        playerAttackValue : 1,
        playerDefendValue : 87,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 70,
        playerName : "塞兰特斯",
        playerAttackValue : 1,
        playerDefendValue : 81,
        playerSpeedValue : 61,
        playerPosition : 2,
    },
    {
        playerId : 71,
        playerName : "马修-瑞安",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 60,
        playerPosition : 2,
    },
    {
        playerId : 72,
        playerName : "汉达诺维奇",
        playerAttackValue : 1,
        playerDefendValue : 86,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 73,
        playerName : "阿森霍",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 74,
        playerName : "布拉沃",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 75,
        playerName : "贝戈维奇",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 55,
        playerPosition : 2,
    },
    {
        playerId : 76,
        playerName : "沃尔姆",
        playerAttackValue : 1,
        playerDefendValue : 79,
        playerSpeedValue : 58,
        playerPosition : 2,
    },
    {
        playerId : 77,
        playerName : "雷纳",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 57,
        playerPosition : 2,
    },
    {
        playerId : 78,
        playerName : "阿雷奥拉",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 53,
        playerPosition : 2,
    },
    {
        playerId : 79,
        playerName : "罗斯尔",
        playerAttackValue : 1,
        playerDefendValue : 79,
        playerSpeedValue : 57,
        playerPosition : 2,
    },
    {
        playerId : 80,
        playerName : "安德雷斯-费尔南德斯",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 56,
        playerPosition : 2,
    },
    {
        playerId : 81,
        playerName : "哈尔多松",
        playerAttackValue : 1,
        playerDefendValue : 100,
        playerSpeedValue : 100,
        playerPosition : 2,
    },
    {
        playerId : 82,
        playerName : "贝莱林",
        playerAttackValue : 51,
        playerDefendValue : 75,
        playerSpeedValue : 95,
        playerPosition : 0,
    },
    {
        playerId : 83,
        playerName : "弗洛伦齐",
        playerAttackValue : 79,
        playerDefendValue : 76,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 84,
        playerName : "比达尔",
        playerAttackValue : 81,
        playerDefendValue : 84,
        playerSpeedValue : 77,
        playerPosition : 0,
    },
    {
        playerId : 85,
        playerName : "纳因戈兰",
        playerAttackValue : 80,
        playerDefendValue : 81,
        playerSpeedValue : 79,
        playerPosition : 0,
    },
    {
        playerId : 86,
        playerName : "皮什切克",
        playerAttackValue : 66,
        playerDefendValue : 81,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 87,
        playerName : "利希施泰纳",
        playerAttackValue : 59,
        playerDefendValue : 79,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 88,
        playerName : "达米安",
        playerAttackValue : 58,
        playerDefendValue : 80,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 89,
        playerName : "埃弗拉",
        playerAttackValue : 51,
        playerDefendValue : 83,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 90,
        playerName : "莫雷诺",
        playerAttackValue : 68,
        playerDefendValue : 70,
        playerSpeedValue : 89,
        playerPosition : 1,
    },
    {
        playerId : 91,
        playerName : "范安霍尔特",
        playerAttackValue : 62,
        playerDefendValue : 71,
        playerSpeedValue : 88,
        playerPosition : 1,
    },
    {
        playerId : 92,
        playerName : "西迪贝",
        playerAttackValue : 67,
        playerDefendValue : 77,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 93,
        playerName : "豪梅-科斯塔",
        playerAttackValue : 59,
        playerDefendValue : 76,
        playerSpeedValue : 83,
        playerPosition : 1,
    },
    {
        playerId : 94,
        playerName : "史蒂芬-拉杜",
        playerAttackValue : 64,
        playerDefendValue : 84,
        playerSpeedValue : 75,
        playerPosition : 1,
    },
    {
        playerId : 95,
        playerName : "米歇尔-马塞多",
        playerAttackValue : 46,
        playerDefendValue : 70,
        playerSpeedValue : 89,
        playerPosition : 1,
    },
    {
        playerId : 96,
        playerName : "拉云",
        playerAttackValue : 72,
        playerDefendValue : 74,
        playerSpeedValue : 84,
        playerPosition : 1,
    },
    {
        playerId : 97,
        playerName : "达尼洛",
        playerAttackValue : 70,
        playerDefendValue : 78,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 98,
        playerName : "库尔扎瓦",
        playerAttackValue : 69,
        playerDefendValue : 79,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 99,
        playerName : "耶德林",
        playerAttackValue : 51,
        playerDefendValue : 65,
        playerSpeedValue : 93,
        playerPosition : 1,
    },
    {
        playerId : 100,
        playerName : "纳尔多",
        playerAttackValue : 69,
        playerDefendValue : 86,
        playerSpeedValue : 72,
        playerPosition : 1,
    },
    {
        playerId : 101,
        playerName : "弗尔萨利科",
        playerAttackValue : 55,
        playerDefendValue : 77,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 102,
        playerName : "拉斯-迪亚拉",
        playerAttackValue : 53,
        playerDefendValue : 81,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 103,
        playerName : "泰特",
        playerAttackValue : 42,
        playerDefendValue : 79,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 104,
        playerName : "乌姆蒂蒂",
        playerAttackValue : 64,
        playerDefendValue : 82,
        playerSpeedValue : 75,
        playerPosition : 1,
    },
    {
        playerId : 105,
        playerName : "西莫-纳瓦罗",
        playerAttackValue : 47,
        playerDefendValue : 76,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 106,
        playerName : "巴尔特拉",
        playerAttackValue : 46,
        playerDefendValue : 84,
        playerSpeedValue : 73,
        playerPosition : 1,
    },
    {
        playerId : 107,
        playerName : "马尔基尼奥斯",
        playerAttackValue : 38,
        playerDefendValue : 84,
        playerSpeedValue : 73,
        playerPosition : 1,
    },
    {
        playerId : 108,
        playerName : "蒂亚戈-门德斯",
        playerAttackValue : 67,
        playerDefendValue : 71,
        playerSpeedValue : 85,
        playerPosition : 1,
    },
    {
        playerId : 109,
        playerName : "格雷茨卡",
        playerAttackValue : 70,
        playerDefendValue : 75,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 110,
        playerName : "阿达玛-特拉奥雷",
        playerAttackValue : 57,
        playerDefendValue : 70,
        playerSpeedValue : 86,
        playerPosition : 1,
    },
    {
        playerId : 111,
        playerName : "阿兰",
        playerAttackValue : 64,
        playerDefendValue : 79,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 112,
        playerName : "马尔基西奥",
        playerAttackValue : 74,
        playerDefendValue : 76,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 113,
        playerName : "鲁西隆",
        playerAttackValue : 62,
        playerDefendValue : 70,
        playerSpeedValue : 85,
        playerPosition : 1,
    },
    {
        playerId : 114,
        playerName : "A-图雷",
        playerAttackValue : 51,
        playerDefendValue : 74,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 115,
        playerName : "巴勒",
        playerAttackValue : 49,
        playerDefendValue : 73,
        playerSpeedValue : 82,
        playerPosition : 1,
    },
    {
        playerId : 116,
        playerName : "阿奇姆彭",
        playerAttackValue : 65,
        playerDefendValue : 63,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 117,
        playerName : "桑松",
        playerAttackValue : 75,
        playerDefendValue : 77,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 118,
        playerName : "里卡多-罗德里格斯",
        playerAttackValue : 67,
        playerDefendValue : 80,
        playerSpeedValue : 74,
        playerPosition : 1,
    },
    {
        playerId : 119,
        playerName : "拉斐尔",
        playerAttackValue : 57,
        playerDefendValue : 74,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 120,
        playerName : "佩兰",
        playerAttackValue : 65,
        playerDefendValue : 84,
        playerSpeedValue : 70,
        playerPosition : 1,
    },
    {
        playerId : 121,
        playerName : "贝尔奇切",
        playerAttackValue : 55,
        playerDefendValue : 76,
        playerSpeedValue : 78,
        playerPosition : 1,
    },
    {
        playerId : 122,
        playerName : "马塞尔-里瑟",
        playerAttackValue : 76,
        playerDefendValue : 67,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 123,
        playerName : "西普里安",
        playerAttackValue : 75,
        playerDefendValue : 73,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 124,
        playerName : "达波",
        playerAttackValue : 71,
        playerDefendValue : 74,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 125,
        playerName : "拉米雷斯",
        playerAttackValue : 73,
        playerDefendValue : 77,
        playerSpeedValue : 76,
        playerPosition : 0,
    },
    {
        playerId : 126,
        playerName : "阿马维",
        playerAttackValue : 67,
        playerDefendValue : 74,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 127,
        playerName : "科杰洛",
        playerAttackValue : 66,
        playerDefendValue : 75,
        playerSpeedValue : 78,
        playerPosition : 1,
    },
    {
        playerId : 128,
        playerName : "德比希",
        playerAttackValue : 65,
        playerDefendValue : 79,
        playerSpeedValue : 74,
        playerPosition : 1,
    },
    {
        playerId : 129,
        playerName : "巴斯蒂安斯",
        playerAttackValue : 59,
        playerDefendValue : 73,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 130,
        playerName : "胡梅尔斯",
        playerAttackValue : 58,
        playerDefendValue : 89,
        playerSpeedValue : 64,
        playerPosition : 1,
    },
    {
        playerId : 131,
        playerName : "普恩杰",
        playerAttackValue : 34,
        playerDefendValue : 70,
        playerSpeedValue : 83,
        playerPosition : 1,
    },
    {
        playerId : 132,
        playerName : "塞纳德-卢利奇",
        playerAttackValue : 72,
        playerDefendValue : 71,
        playerSpeedValue : 81,
        playerPosition : 1,
    },
    {
        playerId : 133,
        playerName : "格雷罗",
        playerAttackValue : 72,
        playerDefendValue : 73,
        playerSpeedValue : 79,
        playerPosition : 1,
    },
    {
        playerId : 134,
        playerName : "阿萨莫阿",
        playerAttackValue : 73,
        playerDefendValue : 71,
        playerSpeedValue : 80,
        playerPosition : 1,
    },
    {
        playerId : 135,
        playerName : "托利索",
        playerAttackValue : 76,
        playerDefendValue : 76,
        playerSpeedValue : 75,
        playerPosition : 1,
    },
    {
        playerId : 136,
        playerName : "马斯切拉诺",
        playerAttackValue : 53,
        playerDefendValue : 85,
        playerSpeedValue : 66,
        playerPosition : 1,
    },
    {
        playerId : 137,
        playerName : "德罗西",
        playerAttackValue : 64,
        playerDefendValue : 81,
        playerSpeedValue : 69,
        playerPosition : 1,
    },
    {
        playerId : 138,
        playerName : "拉斯-本德",
        playerAttackValue : 64,
        playerDefendValue : 82,
        playerSpeedValue : 68,
        playerPosition : 1,
    },
    {
        playerId : 139,
        playerName : "帕罗洛",
        playerAttackValue : 77,
        playerDefendValue : 76,
        playerSpeedValue : 73,
        playerPosition : 1,
    },
    {
        playerId : 140,
        playerName : "戈纳隆",
        playerAttackValue : 62,
        playerDefendValue : 82,
        playerSpeedValue : 67,
        playerPosition : 1,
    },
    {
        playerId : 141,
        playerName : "桑德罗",
        playerAttackValue : 69,
        playerDefendValue : 76,
        playerSpeedValue : 72,
        playerPosition : 1,
    },
    {
        playerId : 142,
        playerName : "特谢拉",
        playerAttackValue : 79,
        playerDefendValue : 60,
        playerSpeedValue : 87,
        playerPosition : 0,
    },
    {
        playerId : 143,
        playerName : "特谢拉",
        playerAttackValue : 79,
        playerDefendValue : 60,
        playerSpeedValue : 87,
        playerPosition : 1,
    },
    {
        playerId : 144,
        playerName : "卡斯特罗",
        playerAttackValue : 72,
        playerDefendValue : 73,
        playerSpeedValue : 74,
        playerPosition : 1,
    },
    {
        playerId : 145,
        playerName : "德莱尼",
        playerAttackValue : 71,
        playerDefendValue : 74,
        playerSpeedValue : 73,
        playerPosition : 1,
    },
    {
        playerId : 146,
        playerName : "赫迪拉",
        playerAttackValue : 76,
        playerDefendValue : 81,
        playerSpeedValue : 66,
        playerPosition : 1,
    },
    {
        playerId : 147,
        playerName : "基米希",
        playerAttackValue : 67,
        playerDefendValue : 76,
        playerSpeedValue : 71,
        playerPosition : 1,
    },
    {
        playerId : 148,
        playerName : "尤努佐维奇",
        playerAttackValue : 72,
        playerDefendValue : 69,
        playerSpeedValue : 77,
        playerPosition : 1,
    },
    {
        playerId : 149,
        playerName : "斯特罗曼",
        playerAttackValue : 74,
        playerDefendValue : 78,
        playerSpeedValue : 68,
        playerPosition : 1,
    },
    {
        playerId : 150,
        playerName : "科拉罗夫",
        playerAttackValue : 69,
        playerDefendValue : 79,
        playerSpeedValue : 67,
        playerPosition : 1,
    },
    {
        playerId : 151,
        playerName : "米林科维奇-萨维奇",
        playerAttackValue : 70,
        playerDefendValue : 73,
        playerSpeedValue : 72,
        playerPosition : 1,
    },
    {
        playerId : 152,
        playerName : "维特塞尔",
        playerAttackValue : 74,
        playerDefendValue : 73,
        playerSpeedValue : 71,
        playerPosition : 1,
    },
    {
        playerId : 153,
        playerName : "因苏亚",
        playerAttackValue : 65,
        playerDefendValue : 77,
        playerSpeedValue : 67,
        playerPosition : 1,
    },
    {
        playerId : 154,
        playerName : "吉尔",
        playerAttackValue : 39,
        playerDefendValue : 81,
        playerSpeedValue : 63,
        playerPosition : 1,
    },
    {
        playerId : 155,
        playerName : "张琳芃",
        playerAttackValue : 67,
        playerDefendValue : 69,
        playerSpeedValue : 74,
        playerPosition : 1,
    },
    {
        playerId : 156,
        playerName : "艾哈迈多夫",
        playerAttackValue : 70,
        playerDefendValue : 72,
        playerSpeedValue : 69,
        playerPosition : 1,
    },
    {
        playerId : 157,
        playerName : "斯特林",
        playerAttackValue : 71,
        playerDefendValue : 46,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 158,
        playerName : "卡洛斯-桑切斯",
        playerAttackValue : 73,
        playerDefendValue : 49,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 159,
        playerName : "王燊超",
        playerAttackValue : 27,
        playerDefendValue : 66,
        playerSpeedValue : 72,
        playerPosition : 1,
    },
    {
        playerId : 160,
        playerName : "若泽-丰特",
        playerAttackValue : 35,
        playerDefendValue : 84,
        playerSpeedValue : 54,
        playerPosition : 1,
    },
    {
        playerId : 161,
        playerName : "帕莱塔",
        playerAttackValue : 33,
        playerDefendValue : 83,
        playerSpeedValue : 55,
        playerPosition : 1,
    },
    {
        playerId : 162,
        playerName : "卢卡斯-莫拉",
        playerAttackValue : 74,
        playerDefendValue : 44,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 163,
        playerName : "萨拉赫",
        playerAttackValue : 72,
        playerDefendValue : 45,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 164,
        playerName : "哈恩",
        playerAttackValue : 78,
        playerDefendValue : 52,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 165,
        playerName : "坎德雷瓦",
        playerAttackValue : 80,
        playerDefendValue : 56,
        playerSpeedValue : 81,
        playerPosition : 0,
    },
    {
        playerId : 166,
        playerName : "奥古斯托-费尔南德斯",
        playerAttackValue : 70,
        playerDefendValue : 68,
        playerSpeedValue : 69,
        playerPosition : 1,
    },
    {
        playerId : 167,
        playerName : "维罗索",
        playerAttackValue : 70,
        playerDefendValue : 73,
        playerSpeedValue : 64,
        playerPosition : 1,
    },
    {
        playerId : 168,
        playerName : "波兰斯基",
        playerAttackValue : 71,
        playerDefendValue : 78,
        playerSpeedValue : 59,
        playerPosition : 1,
    },
    {
        playerId : 169,
        playerName : "托西奇",
        playerAttackValue : 47,
        playerDefendValue : 74,
        playerSpeedValue : 63,
        playerPosition : 1,
    },
    {
        playerId : 170,
        playerName : "胡安-卡拉",
        playerAttackValue : 54,
        playerDefendValue : 72,
        playerSpeedValue : 64,
        playerPosition : 1,
    },
    {
        playerId : 171,
        playerName : "鲁利",
        playerAttackValue : 1,
        playerDefendValue : 85,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 172,
        playerName : "姆巴佩",
        playerAttackValue : 73,
        playerDefendValue : 47,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 173,
        playerName : "施廷德尔",
        playerAttackValue : 83,
        playerDefendValue : 65,
        playerSpeedValue : 70,
        playerPosition : 1,
    },
    {
        playerId : 174,
        playerName : "黄博文",
        playerAttackValue : 65,
        playerDefendValue : 64,
        playerSpeedValue : 71,
        playerPosition : 0,
    },
    {
        playerId : 175,
        playerName : "黄博文",
        playerAttackValue : 65,
        playerDefendValue : 64,
        playerSpeedValue : 71,
        playerPosition : 1,
    },
    {
        playerId : 176,
        playerName : "施维格勒",
        playerAttackValue : 69,
        playerDefendValue : 74,
        playerSpeedValue : 61,
        playerPosition : 1,
    },
    {
        playerId : 177,
        playerName : "柏佳骏",
        playerAttackValue : 34,
        playerDefendValue : 62,
        playerSpeedValue : 73,
        playerPosition : 1,
    },
    {
        playerId : 178,
        playerName : "苏巴西奇",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 53,
        playerPosition : 2,
    },
    {
        playerId : 179,
        playerName : "奥布拉克",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 52,
        playerPosition : 2,
    },
    {
        playerId : 180,
        playerName : "内托",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 181,
        playerName : "迪马利亚",
        playerAttackValue : 79,
        playerDefendValue : 47,
        playerSpeedValue : 87,
        playerPosition : 0,
    },
    {
        playerId : 182,
        playerName : "塔利斯卡",
        playerAttackValue : 80,
        playerDefendValue : 59,
        playerSpeedValue : 75,
        playerPosition : 1,
    },
    {
        playerId : 183,
        playerName : "奥古斯托",
        playerAttackValue : 73,
        playerDefendValue : 66,
        playerSpeedValue : 68,
        playerPosition : 1,
    },
    {
        playerId : 184,
        playerName : "蒿俊闵",
        playerAttackValue : 60,
        playerDefendValue : 63,
        playerSpeedValue : 71,
        playerPosition : 1,
    },
    {
        playerId : 185,
        playerName : "胡安-索里亚诺",
        playerAttackValue : 1,
        playerDefendValue : 69,
        playerSpeedValue : 65,
        playerPosition : 2,
    },
    {
        playerId : 186,
        playerName : "安东尼",
        playerAttackValue : 1,
        playerDefendValue : 71,
        playerSpeedValue : 63,
        playerPosition : 2,
    },
    {
        playerId : 187,
        playerName : "约埃尔",
        playerAttackValue : 1,
        playerDefendValue : 74,
        playerSpeedValue : 60,
        playerPosition : 2,
    },
    {
        playerId : 188,
        playerName : "索默",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 189,
        playerName : "西里古",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 190,
        playerName : "多纳鲁马",
        playerAttackValue : 1,
        playerDefendValue : 86,
        playerSpeedValue : 48,
        playerPosition : 2,
    },
    {
        playerId : 191,
        playerName : "曼丹达",
        playerAttackValue : 1,
        playerDefendValue : 86,
        playerSpeedValue : 48,
        playerPosition : 2,
    },
    {
        playerId : 192,
        playerName : "科斯蒂尔",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 193,
        playerName : "布冯",
        playerAttackValue : 1,
        playerDefendValue : 87,
        playerSpeedValue : 46,
        playerPosition : 2,
    },
    {
        playerId : 194,
        playerName : "科雷亚",
        playerAttackValue : 79,
        playerDefendValue : 49,
        playerSpeedValue : 83,
        playerPosition : 0,
    },
    {
        playerId : 195,
        playerName : "格拉德尔",
        playerAttackValue : 74,
        playerDefendValue : 44,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 196,
        playerName : "纳库尔马",
        playerAttackValue : 70,
        playerDefendValue : 41,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 197,
        playerName : "巴尔博萨",
        playerAttackValue : 1,
        playerDefendValue : 75,
        playerSpeedValue : 57,
        playerPosition : 2,
    },
    {
        playerId : 198,
        playerName : "布尔基",
        playerAttackValue : 1,
        playerDefendValue : 81,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 199,
        playerName : "特拉普",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 49,
        playerPosition : 2,
    },
    {
        playerId : 200,
        playerName : "格纳布里",
        playerAttackValue : 74,
        playerDefendValue : 43,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 201,
        playerName : "吴曦",
        playerAttackValue : 65,
        playerDefendValue : 63,
        playerSpeedValue : 68,
        playerPosition : 1,
    },
    {
        playerId : 202,
        playerName : "克拉夫特",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 203,
        playerName : "比特勒",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 51,
        playerPosition : 2,
    },
    {
        playerId : 204,
        playerName : "奥利弗-鲍曼",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 49,
        playerPosition : 2,
    },
    {
        playerId : 205,
        playerName : "霍埃尔-坎贝尔",
        playerAttackValue : 73,
        playerDefendValue : 42,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 206,
        playerName : "孙可",
        playerAttackValue : 57,
        playerDefendValue : 52,
        playerSpeedValue : 78,
        playerPosition : 0,
    },
    {
        playerId : 207,
        playerName : "根特纳",
        playerAttackValue : 74,
        playerDefendValue : 75,
        playerSpeedValue : 55,
        playerPosition : 1,
    },
    {
        playerId : 208,
        playerName : "吕菲耶",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 48,
        playerPosition : 2,
    },
    {
        playerId : 209,
        playerName : "菲利普-科斯蒂奇",
        playerAttackValue : 71,
        playerDefendValue : 39,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 210,
        playerName : "韩鹏",
        playerAttackValue : 72,
        playerDefendValue : 45,
        playerSpeedValue : 84,
        playerPosition : 0,
    },
    {
        playerId : 211,
        playerName : "努尔丁-阿姆拉巴特",
        playerAttackValue : 76,
        playerDefendValue : 42,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 212,
        playerName : "萨利布尔",
        playerAttackValue : 73,
        playerDefendValue : 39,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 213,
        playerName : "郜林",
        playerAttackValue : 67,
        playerDefendValue : 56,
        playerSpeedValue : 72,
        playerPosition : 0,
    },
    {
        playerId : 214,
        playerName : "霍恩",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 48,
        playerPosition : 2,
    },
    {
        playerId : 215,
        playerName : "什琴斯尼",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 45,
        playerPosition : 2,
    },
    {
        playerId : 216,
        playerName : "恩库杜",
        playerAttackValue : 72,
        playerDefendValue : 35,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 217,
        playerName : "布鲁马",
        playerAttackValue : 71,
        playerDefendValue : 34,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 218,
        playerName : "斯波尔蒂耶洛",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 43,
        playerPosition : 2,
    },
    {
        playerId : 219,
        playerName : "费利佩-安德森",
        playerAttackValue : 75,
        playerDefendValue : 34,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 220,
        playerName : "佩里西奇",
        playerAttackValue : 79,
        playerDefendValue : 42,
        playerSpeedValue : 84,
        playerPosition : 0,
    },
    {
        playerId : 221,
        playerName : "格尔戈林",
        playerAttackValue : 1,
        playerDefendValue : 76,
        playerSpeedValue : 50,
        playerPosition : 2,
    },
    {
        playerId : 222,
        playerName : "希茨",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 44,
        playerPosition : 2,
    },
    {
        playerId : 223,
        playerName : "费尔曼",
        playerAttackValue : 1,
        playerDefendValue : 83,
        playerSpeedValue : 43,
        playerPosition : 2,
    },
    {
        playerId : 224,
        playerName : "威尔逊",
        playerAttackValue : 73,
        playerDefendValue : 34,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 225,
        playerName : "梅尔滕斯",
        playerAttackValue : 75,
        playerDefendValue : 36,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 226,
        playerName : "卡斯特尔斯",
        playerAttackValue : 1,
        playerDefendValue : 80,
        playerSpeedValue : 45,
        playerPosition : 2,
    },
    {
        playerId : 227,
        playerName : "米兰特",
        playerAttackValue : 1,
        playerDefendValue : 82,
        playerSpeedValue : 43,
        playerPosition : 2,
    },
    {
        playerId : 228,
        playerName : "托马斯-穆勒",
        playerAttackValue : 83,
        playerDefendValue : 46,
        playerSpeedValue : 78,
        playerPosition : 0,
    },
    {
        playerId : 229,
        playerName : "孔西利",
        playerAttackValue : 1,
        playerDefendValue : 84,
        playerSpeedValue : 40,
        playerPosition : 2,
    },
    {
        playerId : 230,
        playerName : "卡里略",
        playerAttackValue : 76,
        playerDefendValue : 32,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 231,
        playerName : "贝拉拉比",
        playerAttackValue : 77,
        playerDefendValue : 33,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 232,
        playerName : "巴坎布",
        playerAttackValue : 78,
        playerDefendValue : 35,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 233,
        playerName : "奥斯曼-登贝莱",
        playerAttackValue : 73,
        playerDefendValue : 31,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 234,
        playerName : "埃斯维因",
        playerAttackValue : 72,
        playerDefendValue : 32,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 235,
        playerName : "恩吉耶",
        playerAttackValue : 68,
        playerDefendValue : 30,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 236,
        playerName : "普利亚",
        playerAttackValue : 79,
        playerDefendValue : 41,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 237,
        playerName : "赫尔曼",
        playerAttackValue : 75,
        playerDefendValue : 31,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 238,
        playerName : "本-阿尔法",
        playerAttackValue : 82,
        playerDefendValue : 40,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 239,
        playerName : "格德斯",
        playerAttackValue : 76,
        playerDefendValue : 35,
        playerSpeedValue : 87,
        playerPosition : 0,
    },
    {
        playerId : 240,
        playerName : "卡马诺",
        playerAttackValue : 69,
        playerDefendValue : 32,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 241,
        playerName : "汤森",
        playerAttackValue : 75,
        playerDefendValue : 32,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 242,
        playerName : "亚历杭德罗-戈麦斯",
        playerAttackValue : 74,
        playerDefendValue : 31,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 243,
        playerName : "黑勒",
        playerAttackValue : 70,
        playerDefendValue : 28,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 244,
        playerName : "伊哈洛",
        playerAttackValue : 73,
        playerDefendValue : 40,
        playerSpeedValue : 81,
        playerPosition : 0,
    },
    {
        playerId : 245,
        playerName : "德佩",
        playerAttackValue : 77,
        playerDefendValue : 30,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 246,
        playerName : "凯塔-巴尔德",
        playerAttackValue : 76,
        playerDefendValue : 29,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 247,
        playerName : "穆坎乔",
        playerAttackValue : 76,
        playerDefendValue : 29,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 248,
        playerName : "埃泽杰尔",
        playerAttackValue : 74,
        playerDefendValue : 28,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 249,
        playerName : "因莫比莱",
        playerAttackValue : 83,
        playerDefendValue : 38,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 250,
        playerName : "热尔维尼奥",
        playerAttackValue : 69,
        playerDefendValue : 28,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 251,
        playerName : "曾诚",
        playerAttackValue : 1,
        playerDefendValue : 70,
        playerSpeedValue : 50,
        playerPosition : 2,
    },
    {
        playerId : 252,
        playerName : "乌尔赖希",
        playerAttackValue : 1,
        playerDefendValue : 81,
        playerSpeedValue : 39,
        playerPosition : 2,
    },
    {
        playerId : 253,
        playerName : "布莱斯维特",
        playerAttackValue : 76,
        playerDefendValue : 34,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 254,
        playerName : "维尔纳",
        playerAttackValue : 75,
        playerDefendValue : 27,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 255,
        playerName : "沙拉维",
        playerAttackValue : 75,
        playerDefendValue : 31,
        playerSpeedValue : 87,
        playerPosition : 0,
    },
    {
        playerId : 256,
        playerName : "加克佩",
        playerAttackValue : 70,
        playerDefendValue : 28,
        playerSpeedValue : 90,
        playerPosition : 0,
    },
    {
        playerId : 257,
        playerName : "卡瓦尼",
        playerAttackValue : 83,
        playerDefendValue : 42,
        playerSpeedValue : 76,
        playerPosition : 0,
    },
    {
        playerId : 258,
        playerName : "恩特普",
        playerAttackValue : 75,
        playerDefendValue : 26,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 259,
        playerName : "卡拉斯科",
        playerAttackValue : 78,
        playerDefendValue : 29,
        playerSpeedValue : 88,
        playerPosition : 0,
    },
    {
        playerId : 260,
        playerName : "德普列维尔",
        playerAttackValue : 75,
        playerDefendValue : 33,
        playerSpeedValue : 84,
        playerPosition : 0,
    },
    {
        playerId : 261,
        playerName : "于汉超",
        playerAttackValue : 64,
        playerDefendValue : 41,
        playerSpeedValue : 76,
        playerPosition : 0,
    },
    {
        playerId : 262,
        playerName : "卢卡库",
        playerAttackValue : 82,
        playerDefendValue : 34,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 263,
        playerName : "利昂-贝利",
        playerAttackValue : 70,
        playerDefendValue : 23,
        playerSpeedValue : 93,
        playerPosition : 0,
    },
    {
        playerId : 264,
        playerName : "特略",
        playerAttackValue : 70,
        playerDefendValue : 24,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 265,
        playerName : "哈梅斯-罗德里格斯",
        playerAttackValue : 85,
        playerDefendValue : 40,
        playerSpeedValue : 76,
        playerPosition : 0,
    },
    {
        playerId : 266,
        playerName : "贝拉尔迪",
        playerAttackValue : 80,
        playerDefendValue : 30,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 267,
        playerName : "尼昂",
        playerAttackValue : 74,
        playerDefendValue : 26,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 268,
        playerName : "武磊",
        playerAttackValue : 72,
        playerDefendValue : 31,
        playerSpeedValue : 84,
        playerPosition : 0,
    },
    {
        playerId : 269,
        playerName : "拉维奇",
        playerAttackValue : 71,
        playerDefendValue : 33,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 270,
        playerName : "张鹭",
        playerAttackValue : 1,
        playerDefendValue : 70,
        playerSpeedValue : 45,
        playerPosition : 2,
    },
    {
        playerId : 271,
        playerName : "安德烈-格雷",
        playerAttackValue : 74,
        playerDefendValue : 23,
        playerSpeedValue : 91,
        playerPosition : 0,
    },
    {
        playerId : 272,
        playerName : "马尔科-萨乌",
        playerAttackValue : 72,
        playerDefendValue : 22,
        playerSpeedValue : 92,
        playerPosition : 0,
    },
    {
        playerId : 273,
        playerName : "加梅罗",
        playerAttackValue : 84,
        playerDefendValue : 35,
        playerSpeedValue : 79,
        playerPosition : 0,
    },
    {
        playerId : 274,
        playerName : "因西涅",
        playerAttackValue : 72,
        playerDefendValue : 25,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 275,
        playerName : "费基尔",
        playerAttackValue : 77,
        playerDefendValue : 31,
        playerSpeedValue : 83,
        playerPosition : 0,
    },
    {
        playerId : 276,
        playerName : "帕托",
        playerAttackValue : 78,
        playerDefendValue : 27,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 277,
        playerName : "维维亚诺",
        playerAttackValue : 1,
        playerDefendValue : 81,
        playerSpeedValue : 32,
        playerPosition : 2,
    },
    {
        playerId : 278,
        playerName : "阿斯帕斯",
        playerAttackValue : 82,
        playerDefendValue : 29,
        playerSpeedValue : 83,
        playerPosition : 0,
    },
    {
        playerId : 279,
        playerName : "穆里尔",
        playerAttackValue : 74,
        playerDefendValue : 23,
        playerSpeedValue : 89,
        playerPosition : 0,
    },
    {
        playerId : 280,
        playerName : "颜骏凌",
        playerAttackValue : 1,
        playerDefendValue : 69,
        playerSpeedValue : 43,
        playerPosition : 2,
    },
    {
        playerId : 281,
        playerName : "孙兴慜",
        playerAttackValue : 81,
        playerDefendValue : 25,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 282,
        playerName : "约维蒂奇",
        playerAttackValue : 82,
        playerDefendValue : 33,
        playerSpeedValue : 78,
        playerPosition : 0,
    },
    {
        playerId : 283,
        playerName : "顾超",
        playerAttackValue : 1,
        playerDefendValue : 69,
        playerSpeedValue : 42,
        playerPosition : 2,
    },
    {
        playerId : 284,
        playerName : "埃德尔",
        playerAttackValue : 80,
        playerDefendValue : 25,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 285,
        playerName : "巴舒亚伊",
        playerAttackValue : 80,
        playerDefendValue : 27,
        playerSpeedValue : 83,
        playerPosition : 0,
    },
    {
        playerId : 286,
        playerName : "莫德斯特",
        playerAttackValue : 82,
        playerDefendValue : 33,
        playerSpeedValue : 77,
        playerPosition : 0,
    },
    {
        playerId : 287,
        playerName : "张思鹏",
        playerAttackValue : 1,
        playerDefendValue : 65,
        playerSpeedValue : 45,
        playerPosition : 2,
    },
    {
        playerId : 288,
        playerName : "巴卡",
        playerAttackValue : 81,
        playerDefendValue : 24,
        playerSpeedValue : 85,
        playerPosition : 0,
    },
    {
        playerId : 289,
        playerName : "科尔内",
        playerAttackValue : 73,
        playerDefendValue : 22,
        playerSpeedValue : 86,
        playerPosition : 0,
    },
    {
        playerId : 290,
        playerName : "杨智",
        playerAttackValue : 1,
        playerDefendValue : 63,
        playerSpeedValue : 44,
        playerPosition : 2,
    },
    {
        playerId : 291,
        playerName : "郭全博",
        playerAttackValue : 1,
        playerDefendValue : 64,
        playerSpeedValue : 43,
        playerPosition : 2,
    },
    {
        playerId : 292,
        playerName : "隋维杰",
        playerAttackValue : 1,
        playerDefendValue : 65,
        playerSpeedValue : 42,
        playerPosition : 2,
    },
    {
        playerId : 293,
        playerName : "罗西",
        playerAttackValue : 81,
        playerDefendValue : 23,
        playerSpeedValue : 82,
        playerPosition : 0,
    },
    {
        playerId : 294,
        playerName : "伊卡尔迪",
        playerAttackValue : 82,
        playerDefendValue : 26,
        playerSpeedValue : 79,
        playerPosition : 0,
    },
    {
        playerId : 295,
        playerName : "王大雷",
        playerAttackValue : 1,
        playerDefendValue : 74,
        playerSpeedValue : 31,
        playerPosition : 2,
    },
    {
        playerId : 296,
        playerName : "伊瓜因",
        playerAttackValue : 87,
        playerDefendValue : 24,
        playerSpeedValue : 80,
        playerPosition : 0,
    },
    {
        playerId : 297,
        playerName : "本泽马",
        playerAttackValue : 84,
        playerDefendValue : 22,
        playerSpeedValue : 81,
        playerPosition : 0,
    },
    {
        playerId : 298,
        playerName : "于大宝",
        playerAttackValue : 67,
        playerDefendValue : 30,
        playerSpeedValue : 73,
        playerPosition : 0,
    },
    {
        playerId : 299,
        playerName : "刘殿座",
        playerAttackValue : 1,
        playerDefendValue : 62,
        playerSpeedValue : 40,
        playerPosition : 2,
    },
    {
        playerId : 300,
        playerName : "姜宁",
        playerAttackValue : 66,
        playerDefendValue : 19,
        playerSpeedValue : 78,
        playerPosition : 0,
    }
]
const get_player =  function(playerId){
    return player[playerId]
}
module.exports = {
    get_player
}
